### ISSUE TITLE
Rewrite injection library

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#111]
I have started putting together some of the code for the [PE](https://github.com/ML4GW/PE) project, and naturally have seen opportunities for generalization, specifically with the `injection` library. This might be a good time to consider how we may implement this in its own repo. Is the injection code large enough to warrant its own repo? If not, what else should go in? related to ML4GW/PE#6

**Comment by wbenoit26** [comment]
I feel that it's large enough on its own at this point, but there are also things that could be added. At the moment, it feels pretty rigid in how it gets used. Generalizing to broader use cases, and maybe making it a bit more user-friendly, could be good improvements to add.

**Comment by EthanMarx** [comment]
I totally agree. 'm a bit confused about the logic behind some of the recent changes we've made to the library. For example, I  liked how the old `generate_gw` expected a fully initialized `WaveformGenerator`. It gets a bit confusing now with the `**waveform_generator_args`, as its not exactly obvious what arguments these can be. Additionally, many of the defaults are hidden behind the `get_waveform_generator` function. 

I think the idea behind these changes was to make [these](https://github.com/ML4GW/BBHNet/blob/main/projects/sandbox/generate_waveforms/generate_waveforms.py#L67#L69) arguments in `generate_waveforms` more general. I think simply passing them to the `generate_waveforms` main function, and then explicity initializing the `waveform_arguments` dict in the `WaveformGenerator` makes the most sense. That way, `generate_gw` is as most general as possible, since the details of the waveform generator are left to the user.

@deepchatterjeeligo let me know your thoughts.

**Comment by deepchatterjeeligo** [comment]
Overall I agree that a redesign is needed. There are several function which are rather long and have parts that are hard to test. But also I have been looking at this code rather recently. But to answer

> It gets a bit confusing now with the **waveform_generator_args, as its not exactly obvious what arguments these can be.

It is all the keyword arguments that go into the bilby waveform generator. In our code, we are wrapping around a bilby function and hence do not need to add them once again to the function signature. If in a new release of bilby, the keyword argument changes to something else, we should don't need a change in our end. We can assume that the user will take note that the bilby version has changed. So I think the docstring should contain a cross ref to the corresponding bilby docs to know what the arguments can be.

However, it is true that the code tries to unwrap a nested dictionary `waveform_arguments`. While I made that change, I don't feel very strongly about it since it break the logic I mentioned above. But I thought that was a preference in #70

**Comment by deepchatterjeeligo** [comment]
> I think the idea behind [these](https://github.com/ML4GW/BBHNet/blob/main/projects/sandbox/generate_waveforms/generate_waveforms.py#L67#L69) changes was to make these arguments in generate_waveforms more general.

I don't see a generate_waveform in injection.py, but if you're suggesting putting all of those keyword arguments explicitly in the function signature, I'll suggest against it.

**Comment by EthanMarx** [comment]
So `generate_waveforms` refers to the [project](https://github.com/ML4GW/BBHNet/tree/main/projects/sandbox/generate_waveforms) it's actually not too bad to add arguments thanks to `typeo`. 

I do see what you mean though. The motivation for this discussion from my end was trying to utilize these same tools for the PE project, where non-CBC waveforms might be used. In that case, some of the default `waveform_arguments` (i.e. `waveform_approximant` and `reference_frequency` aren't relevant). I like the idea of using the `**` syntax for the _waveform_arguments_ , as these are not bilby specific, but dependent on the waveform you pass it. In either case what we have now obviously works fine, I was just thinking about the best way to reduce copy paste between projects.

**Comment by deepchatterjeeligo** [comment]
I will take a closer look at the code for the our project starting this week. I have customized bilby previously for my own projects, and have a overview of the code base, so if something rings a bell, I'll bring it up in our meetings/slack. If there are changes that are in general helpful to bilby, we should consider contributing patches to bilby itself. The bilby-help channel on ligo mattermost is active, we can check with them about a certain design choice before diving in to make a change. In fact, the bilby waveform interface is really a wrapper around lalsimulation python API, and there are ongoing discussions about making that more user friendly. But that maybe a digression at this point, so I am OK punting that down the road and using wrappers around bilby, but also having an eye out for the lalsimulation development.

**Comment by alecgunny** [comment]
Last quick point here: been thinking more about it, and I'm not sure `generate_gw` or the software model that went into it are ripe for generalization. The idea the more I've thought was that there are some project-wide sensible defaults we'd like to use, but rather than make the function signature "all or nothing" (either provide a fully custom waveform generator or accept all of our defaults), you can pick and choose the defaults you want to override more simply.

This obviously makes more sense in a specific context like this, where we know the boundaries of the problem we're trying to solve for right now, and are fine to set them explicitly to simplify development. Not sure if this is entirely what's at issue here but just wanted to clarify the concept behind that API choice, which still might not be ideal.

**Comment by deepchatterjeeligo** [comment]
> rather than make the function signature "all or nothing" (either provide a fully custom waveform generator or accept all of our defaults), you can pick and choose the defaults you want to override more simply.

I agree. In the long run, it will be helpful to have the configuration separately. But I don't know if the scope of this issue was just config. 

For example, in https://github.com/ML4GW/PE/blob/main/libs/injection/mlpe/injection/injection.py, there is another `generate_gw`, and `project_raw_gw`, which is the same in injection lib in BBHNet. So maybe the generalization here is to have refactor the injection lib out in its own thing? @EthanMarx

**Comment by deepchatterjeeligo** [comment]
BTW, by _same_ I meant similarly named. Maybe they are not doing exactly the same thing.

**Comment by EthanMarx** [comment]
Reworking the purpose of this issue: 

1. Use `lalsimulation` directly for generating time domain waveforms
2. Remove reliance on `bilby` `waveform_generator` arguments (will naturally be solved by 1.)
3. Rewrite with machine learning in mind i.e. batch , use torch where possible etc.
