### ISSUE TITLE
Accelerate analysis project

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#135]
Right now, the analysis project is suffering from two sources of bottleneck:
- Timeslides are being integrated, written, then reloaded for building a background distribution. This was necessary when we needed to bin our integrated network outputs since there would be too much to hold in memory at once. Now that we're clustering, this isn't necessary and we can just fit the `ClusterDistribution` as the integrated outputs become available.
- Integration, background fitting, and characterization are all being handled asynchronously in the same process pool used for data loading. The problem is that data loading is a much larger bottleneck than these processes, so the added throughput by parallelizing it is just about equal to running these tasks in serial in the main process. A more optimal implementation would limit the extent to which it tries to submit these tasks to the executor pool (even avoiding doing so entirely) and leave the pool just for reading/writing.

**Comment by EthanMarx** [comment]
How important is keeping track of Segment file names in the `Distribution` objects? The `.fit ` method currently expects Segment objects so that it can do this. To solve the problem outlined in the first bullet, we wan't to be able to call `.fit` before the Segment is written, which is not currently possible. We can easily extend the `.fit` method to take a Tuple of arrays and a `write_dir`, manually infer the filename the same way `write_timeseries` does, and append the filename. However, this leaves it up to the user to ensure the file is written sometime later.

**Comment by alecgunny** [comment]
Ahhh good point I hadn't thought of that. I guess it's not terribly important, the idea was to make it easy to reconstruct where a distribution came from, but that's a bookkeeping task that should probably be left up to the user and not baked into the fundamental functionality of the distribution object (which could be fit on data that's stored in files, but could just as easily be fit on some transient data that just lives in memory)

**Comment by EthanMarx** [comment]
Okay great I agree. Going to remove the `fnames` attribute from the `Distribution` Base class.
