### ISSUE TITLE
Aligning training SNR distribution with desired source mass distribution

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/BBHNet#274]
Our stochastic SNR rescaling scheme during training implicitly shifts the source mass distribution by observing the same frequency content (in the detector frame) but from a different redshift (due to amplitude rescaling). Even ignoring the questions of #196, assuming we just want to align the training and test _mass_ distributions, how can we do this rescaling in a way which preserves the prior mass distribution used to sample the waveforms?

**Comment by rafia17** [comment]
Amplitude rescaling in SNR should not affect the prior mass distribution. It should effect the inclination and luminosity distance but the mass distributions should remain unaffected. @mcoughlin does this align with what we discussed today in our meeting?

**Comment by mcoughlin** [comment]
@rafia17 The BBH problem includes a meaningful frequency shift, which does indeed make it trickier. For BNS, it should be negligible.

**Comment by rafia17** [comment]
Alec's comment: 
the network is still being fit to a rich distribution of events, even if that distribution doesn't exactly match the one used at test time - but it's worth see if there is a way to better align these distributions both because it will probably improve performance and philosophically just has better physical motivations.

Closing with the following assessment:
There is no apparent solution to this issue at present. One workaround is to skip this augmentation step for now if we want to align the train and test mass distributions. But that means reducing our training samples, which is not desirable. So leaving it as it is.
