### ISSUE TITLE
'De-constrain' libraries and projects python versions

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#59]
There seems to be some inconsistencies in python versions between libraries and projects. As I don't think any of the libraries are that sensitive to python versions (say, e.g., between 3.9/ 3.10), we should have looser restrictions.

**Comment by alecgunny** [comment]
One thing to maybe be aware of here is how Poetry will handle installing to a conda environment that uses python 3.9 if the `poetry.lock` has resolved to using 3.10

**Comment by alecgunny** [comment]
Trying to compile my export project and running into these issues, so just going to go through and standardize everything to `">=3.8,<3.11"`. I think having some limits will be useful, especially since I'm adding the `hermes` libraries as a submodule, and  those are only explicitly tested for 3.8 and 3.9 at the moment. That said, I don't think allowing 3.10 will be that big a deal as long as we don't use any 3.10 specific syntax (e.g. I think there are some type annotation constructs in 3.10 that `typeo` doesn't yet support). If it becomes an issue, we can always tighten the reins a bit and then advance everything in lock-step
