### ISSUE TITLE
`fir_from_transfer` `ntaps` keyword initialized improperly

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#81]
@alecgunny 
I think this problem is the core of the whitening issue:

Currently the length of the convolutional window we use for whitening is `DEFAULT_FFTLENGTH * sample_rate `  (see [this line](https://github.com/ML4GW/BBHNet/blob/main/libs/data/bbhnet/data/transforms/whitening.py#L66)). However, since our `DEFAULT_FFTLENGTH = 2` and our data is 1s long, this means the convolutional window is longer than our data. The correct way to initialize `ntaps` is with the keyword argument `fduration` As noted [here](https://github.com/gwpy/gwpy/blob/b5f791105efc5f78ce51f35455bcde8a5d36cef3/gwpy/timeseries/timeseries.py#L1689#L1691) in the documentation for the gwpy whitening function. 

As noted [here](https://github.com/gwpy/gwpy/blob/b5f791105efc5f78ce51f35455bcde8a5d36cef3/gwpy/timeseries/timeseries.py#L1728#L1730), there is a 'filter set in' of `0.5 * fduration` of corrupted data. Thus in our case, our entire data segments are being corrupted. 

We can handle this by incorporating a `fduration` argument to the `WhiteningTransform` and fixing the `ntaps` initialization. However, we have to be careful since we'll have `0.5 * fduration` of data corrupted on both the front and back of the sample. If we set `fduration` sufficiently small, this probably won't be an issue. 

Alternatively, we hack the dataloader to pass `kernel_length + fduration` data to the model, and find a way to crop `0.5 * fduration` samples from the front and end of each sample. This is obviously more complicated. 

Let me know your thoughts. For now, I am going to implement the `fduration` keyword arg (or simply a `DEFAULT_FDURATION`) and initialize it to `0.01`.

**Comment by EthanMarx** [comment]
Ultimately I think we need to solve this problem:
```
data = h5py.File(hanford_background)["hoft"][()]
ts = TimeSeries(data, dt = 1/ sample_rate)

whitened_then_cropped = ts.whiten(asd = asd).crop(2,3).value
cropped_then_whitened = ts.crop(2,3).whiten(asd = asd).value

```
Whitening a long segment then cropping to 1 second window produces good results, but
cropping the segment and then performing whitening gives garbage. There must be some combination of arguments
to the whiten function that will produce good behavior.

<img width="413" alt="Screen Shot 2022-06-17 at 2 52 21 PM" src="https://user-images.githubusercontent.com/61295922/174383861-0f032b9c-e440-4022-8fe3-52a33abede69.png">

**Comment by alecgunny** [comment]
I'm not sure that there needs to be a good combination of arguments given the setup of our problem: as you note, longer `fduration` times cause most of our kernel to fall in the "burn-in" period, but shorter `fduration`s give lower-resolution spectral estimates that increase noise on whitening. It might just be that traditional whitening techniques don't make sense to do on kernels this small.

I've build a little interactive app [here](https://app.hex.tech/alecgunny/app/2543dfc1-c3fe-423e-abfc-d6f38ad0db2f/latest) for exploring how some of these arguments interact on a random stretch of data. In particular, you can see that lowering `fduration` introduces a lot of low-frequency artifacts that are undesirable.

We can however achieve some parity with the "full-whitening" scenario at longer `fduration` values by padding the kernel before whitening (in effect, passing a longer `kernel_length` to the dataloader then slicing out the middle in the `WhiteningTransform`). This introduces a little extra compute and memory at the front of the network, but off the top of my head this should be pretty small compared to the forward and backward step. The app shows that we only need about 0.5-1s worth of padding to get reasonably close the full whitening behavior (which aligns with the burn in period you referenced above), so this seems like it might be a decent solution for the short term?

It also won't cost us much at inference time because we stream the data anyway, so all we have to do is store a larger snapshotter state on the inference service and we won't increase our I/O at all.

**Comment by EthanMarx** [comment]
Yes everything you said makes sense. The one thing we have to make sure of, is that the `t0 ` of the signals and glitches stays in the final, post cropped kernel. With our current implementation of the `sample_kernels` function, this isn't always the case. We likely need some additional argument that specifies how much will be cropped and both ends. However, it would be nice to keep this function as general as possible for the usual standardization methods.

**Comment by EthanMarx** [comment]
(Also was having trouble accessing the visualizaiton)
