### ISSUE TITLE
Automatic data visualization

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#91]
Develop an automatic tools that makes plots (timeseries and spectrograms) of data entering the network. 

Since we package the pre-processor with the network, I don't think plotting the data right before entering the network will be that useful, since it is un-whitened . Maybe we create a separate project that mimics all the data preparation, including whitening.

**Comment by alecgunny** [comment]
Couldn't this be a function that optionally takes a `preprocessor` argument that will operate on each `X` value of a dataset before plotting? I suppose it depends where you imagine this living/being used, but my first thought would be in the `train` function which has access to the standalone `preprocessor`.

**Comment by EthanMarx** [comment]
Since I think we specify the preprocessor in the train _project_ as well, I think it might make more sense there.

**Comment by alecgunny** [comment]
Hmm true, but in the train _project_ we don't know if the train _function_ might add some other magic between this preprocessor and the model. Or rather, _we_ know it won't, but it might in the future and in general the average use won't.

Plus it seems like this is a visualization we'll want _every_ training job to implement: you should always know what your data looks like heading into your model, as close to the model as you can get it. So it feels appropriate to add this in to the function that ostensibly handles _all_ training.

**Comment by alecgunny** [comment]
So hex won't do you much good since presumably you're generating these at training time (though working out a way to publish visualizations later might be cool). Bokeh is great if you need the functionality it has: you want to make things interactive, you don't have so much data that holding it all in your browser's HTML will take forever, you want to be able to inspect data more closely (zooming, hovering, etc., which I guess goes along with the interactive piece). However, if you're just trying to sanity check your data by eye, a lot of that might be overkill, just depends on what you want to do with these visualizations.

One thing I've thought about doing for DeepClean is breaking these two pieces up:
- a library with tools for computing the various analyses you might want (e.g. iterating through a dataset, performing preprocessing, grouping by label, then saving these to some file)
- a library for building a standard set of visualizations from these analyses and composing them into dashboards (e.g. like the one [DeepClean publishes](https://ml4gw.github.io/DeepClean/) as part of its CI).

Right now all of these get done in a single project, but organizing them into libraries for composing things more generally and standardizing themes etc. might help.

All this is probably overkill for this exact problem though, but just wanted to put it on the radar as way to maybe think about how to build this solution in a way that will scale to something more general eventually.

**Comment by EthanMarx** [comment]
Closing as this is done [here](https://github.com/ML4GW/BBHNet/blob/main/libs/trainer/bbhnet/trainer/trainer.py#L166#L171)
