### ISSUE TITLE
handling science segments when making timeslides

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#95]
Do we take into account science segments before hand? Or do we let the inference scripts handle that logic? Considering that in an online scenario, we will have to likely build tools that decide whether the data should be analyzed anyway, I am a a proponent of the latter idea. Open to thoughts.

**Comment by EthanMarx** [comment]
Another option would be to have the `segment_name` as an `Optional` parameter. If it is passed, query the corresponding segments and only inject / save timeslides if there are coincidence segments. If it is not passed, inject / timeslide anyway

**Comment by EthanMarx** [comment]
Also, a few different options to consider when time-sliding science segments:

1. Do a full circular timeshift, and then calculate intersection of science times
2. Perform a non-circular, global shift and _then_ calculate the intersection
3.  _First_  calculate the intersection, and then perform a circular timeshift on these individual, intersected segments


Option 1 sounds the easiest to me. In general the circular options make the most sense as they preserve the most livetime, but they probably will induce a weird edge effect (which I don't think will statistically matter, but good to note). 

I'm not sure what Tri did in the past but would be interesting to know.

**Comment by EthanMarx** [comment]
Another thing to consider is that doing a circular time shift requires the additional knowledge of the start and end times of the 'Segment' to reconstruct the shifted interferometers times given the fixed interferometers times.

**Comment by alecgunny** [comment]
If I'm understanding the problem here correctly (and it's not obvious to me that I am) would something like this make sense for querying a segment for timeslide creation:

1. Expose an argument specifying the number of seconds that each `Segment`'s length must be a multiple of. This will be the length of each file written, and segments will consist of multiple files.
2. Expose an argument for the _maximum shift_ you plan on doing (along with a step but that's less relevant here)
3. Search for science segments over `[t0, t0 + duration)` that have at least `N * base_length + max_shift` seconds in them, where `N` is any integer greater than 0
4. For each one of these segments, do a circular shift then slice out `N * base_length` seconds worth of data in the middle that _doesn't_ have data discontinuously stitched from the circularity of the shift (that's why we include the extra `max_shift` seconds worth of data in each segment).

Would something like that make sense/address the issue you're outlining here? The one downside of this approach as I see it is that it would be nice to be able to specify the amount of background you'd like as input argument, and let it infer how many shifts it needs to do to achieve that, but that seems like it would get too complicated too quickly and for our immediate purposes probably isn't important.

**Comment by EthanMarx** [comment]
So in the process of implementing this I sort of changed my mind a bit:

The problem I see with doing multiple circular timeshifts with in the same TimeSlide object is reconstructing the times of the shifted interferometer. To properly know the L1 times (assuming our file labels and times refer to H1), you need the `dt` of the shift, as well as the `start` and `end` times of the segment to know when the wrap around occured.

With a singular global shift, all you need to reconstruct the shifted interferometer times is the `dt` and H1 times which seems much simpler and intuitive to me. 

With all that being said, in the `timeslide_injection` project (which is close to wrapping up), I added a `circular` flag that allows a singular circular time shift: 

1. Science segments between `start` and `stop` are queried for each ifo 
2. The segments are circularly time shifted
3. The intersection of the circularly shifted segments is calculated
4. The raw data from `start` to `stop`  is circularly shifted via `np.roll` to 'mirror' the segments
5. For each segment in the intersection, data is queried and saved. 

I kept this since I already wrote this code and didn't want it to go to waste, although I am envisioning us using the global shift. 

I hope this makes sense

**Comment by EthanMarx** [comment]
Sorry, what exactly is the `segment.shift("dt-0.0").load("livingston")` doing?

**Comment by alecgunny** [comment]
`segment.shift(other_dir)` just tries to create a `Segment` using the same filenames but from a different shift directory (basically just replacing the part of the path of each filename the end of `TimeSlide.root` but before `TimeSlide.field` with `other_dir`), and then `.load` will load the `"livingston"` dataset from those filenames (or replace `"livingston"` with whatever we're naming the individual ifo datasets in these files)

**Comment by alecgunny** [comment]
Ahhh ok I hadn't thought of that, yeah so the suggestion I made above would only make sense in the other shifting paradigm I guess. I think that might break with the current analysis code, but I don't think the inference code relies on this assumption at all.

I'm wondering if there's any advantage to being able to compare the behavior of the NN on one timeshift vs. another (i.e. when Hanford is the same but Livingston has shifted), but I guess it's not obvious to me what that use case would be. Maybe if the network glitches on one timeshift but not another with a similar `dt` that would be an interesting thing worth investigating? But I guess we can always do that in both paradigms, it's just a question of how straightforward it is. Either way, probably not a big deal for the time being, so if you have something implemented here that works feel free to close this.
