### ISSUE TITLE
Adding Segments after TimeSlide init 

### ISSUE THREAD

**Issue by EthanMarx** [ML4GW/BBHNet#97]
The TimeSlide object initializes Segments once after initialization, and never updates. In the timeslide_injection project, there are instances where segments are added after initialization. Thoughts on making the `segments` a `@property`of the `TimeSlide` that updates the segments whenever accessed?

**Comment by alecgunny** [comment]
I guess it would depend on what the use case is. The point of the auto-discovery initially was basically just a cheap way of organizing segments, but outside of that the `TimeSlide` object is pretty useless (sometimes I wonder if this should just have been replaced with a function instead). What's the use case you envision for leveraging a `TimeSlide` after the `segments` have been compiled?

In either case, I'm not sure a `@property` is desirable for something you expect to change a lot, since it might lead to confusing behavior for downstream users (e.g. if I `.append` to this list, should it `.append` to the underlying object?). If you have a `Segment` object, you can always do `TimeSlide.segments.append(segment)`. Or maybe something like a `.update()` method that tells it more explicitly to go and crawl through the directory again?

**Comment by EthanMarx** [comment]
So I was creating `TimeSlide` objects up front with  and then writing to them:
```
raw_ts = TimeSlide(outdir / "dt-1.0", field="raw")
h5.write_timeseries(raw_ts.path, prefix="raw", t=times, **raw_datasets)
```
I can instead flip the order and everything should work out.

**Comment by alecgunny** [comment]
Ahhh ok that makes sense. Yeah maybe the class was overkill, definitely feel free to play with that. I guess there could eventually be some useful functionality for comparing data from one `field` to data in another (e.g. quickly getting the raw data an NN's outputs came from), but it's obviously not in there yet so maybe it's not worth agonizing over. Maybe the `.update()` method is the easiest way to split the baby here? Idk up to you

**Comment by EthanMarx** [comment]
Yes for now I just went with the `update` method.
